# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#source 'git@github.com:l770826421/LKXFrameworkForiOS.git'

target 'LKXAudioVideo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'MBProgressHUD'
  pod 'SDCycleScrollView'
  pod 'Masonry'
  pod 'Reachability'

 target 'LKXAudioVideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end